apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: github-app-secret
  newName: ghcr.io/fluxcd-community/github-app-secret
  newTag: rc-233ff9af

patches:
- patch: |-
    - op: add
      path: /spec/jobTemplate/spec/template/spec/containers/0/args/-
      value: --installationID=123456789
    - op: add
      path: /spec/jobTemplate/spec/template/spec/containers/0/args/-
      value: --appID=123456
  target:
    name: github-app-token-generator
    kind: CronJob
