---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-app-token-generator
  namespace: flux-system
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "flux-github-tokengen"
          containers:
            - name: github-app-secret
              image: github-app-secret
              imagePullPolicy: IfNotPresent
              args:
              - "-v=3"
              - --privateKeyPath=/etc/secret-volume/private-key.pem
              - --secretName=github-app-token
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              securityContext:
                allowPrivilegeEscalation: false
              volumeMounts:
                - mountPath: /etc/secret-volume
                  name: secret-volume
          restartPolicy: OnFailure
          volumes:
            - name: secret-volume
              secret:
                secretName: github-app-private-key
