---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-github-tokengen
  namespace: flux-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-github-tokengen
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-github-tokengen
subjects:
  - kind: ServiceAccount
    name: flux-github-tokengen
    namespace: flux-system